interact_prompt: update to rustyline 4.1
This fixes #14.

```
   Compiling rustyline v2.1.0
error[E0283]: type annotations needed for `std::result::Result<std::string::String, error::ReadlineError>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-2.1.0/src/lib.rs:639:43
    |
636 |     let user_input = readline_edit(prompt, initial, editor, &original_mode);
    |         ---------- consider giving `user_input` the explicit type `std::result::Result<std::string::String, error::ReadlineError>`, where the type parameter `std::string::String` is specified
...
639 |             editor.add_history_entry(line.as_ref());
    |                                           ^^^^^^ cannot infer type for struct `std::string::String`
    |
    = note: cannot satisfy `std::string::String: std::convert::AsRef<_>`

error[E0283]: type annotations needed
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/rustyline-2.1.0/src/history.rs:150:33
    |
150 |             self.add(try!(line).as_ref()); // TODO truncate to MAX_LINE
    |                      -----------^^^^^^--
    |                      |          |
    |                      |          cannot infer type for struct `std::string::String`
    |                      this method call resolves to `&T`
    |
    = note: cannot satisfy `std::string::String: std::convert::AsRef<_>`

error: aborting due to 2 previous errors
```